// packages/html-cli/fixtures/jsx/sample-box.jsx
// JSX ライクなテンプレートリテラル + フラグメントのフィクスチャ

;<>
  {/* JSX fragment + コメント */}
  <section class={`sample-box ${isDark ? '-dark' : ''}`}>
    <header className="hero-header">
      <h1 className="title">{title}</h1>
      <p className="lede">{description}</p>
    </header>

    <div className="feature-list">
      {features.map((feature) => (
        <article
          key={feature.id}
          className={`feature-card ${feature.primary ? '-primary' : ''} ${feature.wide ? '-wide' : ''} ${feature.secondary ? '-secondary' : ''}`}
        >
          <h2 className="title">{feature.title}</h2>
          <p className="body">{feature.body}</p>
          {feature.primary && <button className="button">Primary action</button>}
        </article>
      ))}
    </div>

    {showCta && (
      <section className="cta-section">
        <p className="body">Call to action text.</p>
        <a className="button" href={ctaHref}>
          Go somewhere
        </a>
      </section>
    )}
  </section>
</>

// vscode/spiracss-html-to-scss/fixtures/vue/sample-box.vue
<template>
  <section class="sample-box">
    <header class="hero-header">
      <h1 class="title">{{ title }}</h1>
      <p class="lede">{{ description }}</p>
    </header>

    <div class="feature-list">
      <article
        v-for="feature in features"
        :key="feature.id"
        class="feature-card"
        :class="{
          '-primary': feature.primary,
          '-wide': feature.wide,
          '-secondary': feature.secondary
        }"
        @click="onClick(feature)"
      >
        <h2 class="title">{{ feature.title }}</h2>
        <p class="body">{{ feature.body }}</p>
        <button
          v-if="feature.primary"
          class="button"
        >
          Primary action
        </button>
      </article>
    </div>

    <section
      v-if="showCta"
      class="cta-section"
    >
      <p class="body">Call to action text.</p>
      <a
        class="button"
        :href="ctaHref"
      >
        Go somewhere
      </a>
    </section>
  </section>
</template>
