// vscode/spiracss-html-to-scss/fixtures/vue/sample-box.vue
<template>
  <section class="sample-box">
    <header class="hero-header">
      <h1 class="title">{{ title }}</h1>
      <p class="lede">{{ description }}</p>
    </header>

    <div class="feature-list">
      <article
        v-for="feature in features"
        :key="feature.id"
        class="feature-card"
        :class="{
          '-primary': feature.primary,
          '-wide': feature.wide,
          '-secondary': feature.secondary
        }"
        @click="onClick(feature)"
      >
        <h2 class="title">{{ feature.title }}</h2>
        <p class="body">{{ feature.body }}</p>
        <button
          v-if="feature.primary"
          class="button"
        >
          Primary action
        </button>
      </article>
    </div>

    <section
      v-if="showCta"
      class="cta-section"
    >
      <p class="body">Call to action text.</p>
      <a
        class="button"
        :href="ctaHref"
      >
        Go somewhere
      </a>
    </section>
  </section>
</template>

// packages/html-cli/fixtures/svelte/sample-box.svelte
<section class="sample-box">
  <header class="hero-header">
    <h1 class="title">{title}</h1>
    <p class="lede">{description}</p>
  </header>

  <div class="feature-list">
    {#each features as feature (feature.id)}
      <article
        class="feature-card"
        class:-primary={feature.primary}
        class:-wide={feature.wide}
        class:-secondary={feature.secondary}
        on:click={() => handleClick(feature)}
      >
        <h2 class="title">{feature.title}</h2>
        <p class="body">{feature.body}</p>
        {#if feature.primary}
          <button class="button">Primary action</button>
        {/if}
      </article>
    {/each}
  </div>

  {#if showCta}
    <section class="cta-section">
      <p class="body">Call to action text.</p>
      <a class="button" href={ctaHref}>Go somewhere</a>
    </section>
  {/if}
</section>
